fname = input("Enter your First name: ")
lname = input("Enter your Last name: ")
mname = input("Enter your Middle name: ")
bday = input("Enter your Birthday: ")
gender = input("Enter your Gender: ")
address = input("Enter your Address: ")
course = input("Enter your Course: ")
yearlvl = input("Enter your Year level: ")

print("First name: ", fname)
print("Last Name: ", lname)
print("Middle Name: ", mname)
print("Birthday: ", bday)
print("Gender: ", gender)
print("Address: ", address)
print("Course: ", course)
print("Year Level: ", yearlvl)